config/routes.rb
Rails.application.routes.draw do
  get 'home/show'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'new', to: 'users#new'
  post 'new', to: 'users#create'
  get 'show', to: 'users#index'
  delete 'delete', to: 'users#destroy'
  get 'index', to: 'home#index'
  root 'home#show'
  get 'forms/show', to: 'home#index'
  get 'form1', to: 'forms1#new'
  post 'form1', to: 'forms1#create'
  get 'form2', to: 'forms2#new'
  post 'form2', to: 'forms2#create'
  get 'form3', to: 'forms3#new'
  post 'form3', to: 'forms3#create'
  get 'form4', to: 'forms4#new'
  post 'form4', to: 'forms4#create'
  get 'form5', to: 'forms5#new'
  post 'form5', to: 'forms5#create'
  get 'form6', to: 'forms6#new'
  post 'form6', to: 'forms6#create'
  get 'form7', to: 'forms7#new'
  post 'form7', to: 'forms7#create'
  get 'form8', to: 'forms8#new'
  post 'form8', to: 'forms8#create'
  get 'form9', to: 'forms9#new'
  post 'form9', to: 'forms9#create'
  get 'form10', to: 'forms10#new'
  post 'form10', to: 'forms10#create'
  get 'form11', to: 'forms11#new'
  post 'form11', to: 'forms11#create'
  get 'show1', to: 'forms1#show'
  get 'show2', to: 'forms2#show'
  get 'show3', to: 'forms3#show'
  get 'show4', to: 'forms4#show'
  get 'show5', to: 'forms5#show'
  get 'show6', to: 'forms6#show'
  get 'show7', to: 'forms7#show'
  get 'show8', to: 'forms8#show'
  get 'show9', to: 'forms9#show'
  get 'form8/download', to: 'forms8#download'
  delete 'delete8', to: 'forms8#destroy'
  get 'form1/download', to: 'forms1#download'
  delete 'delete1', to: 'forms1#destroy'
  get 'form2/download', to: 'forms2#download'
  delete 'delete2', to: 'forms2#destroy'
  get 'form3/download', to: 'forms3#download'
  delete 'delete3', to: 'forms3#destroy'
  delete 'delete4', to: 'forms4#destroy'
  delete 'delete5', to: 'forms5#destroy'
  delete 'delete6', to: 'forms6#destroy'
  delete 'delete7', to: 'forms7#destroy'
  get 'form9/download', to: 'forms9#download'
  delete 'delete9', to: 'forms9#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light"style="background-color: #000000;">
  <div class = "container">
    <ul class="navbar-nav mr-auto">
    <%= link_to "مركز حمدي منغو", root_path,class:"nav-link text-white" %>
    </ul>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if logged_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "النماذج", forms_show_path,class:"nav-link text-white" %>
        </li>
      </ul>
      <%end%>
      <ul class="nav navbar-nav ml-auto">
        <% if logged_in? %>
        <% if current_user.admin %>
        <li>
          <%= link_to "الموظفين", show_path,class:"nav-link text-white" %>
        </li>
        <li>
          <%= link_to "انشاء موظف جديد", new_path,class:"nav-link text-white" %>
        </li>
        <%end%>
        <%end%>
        <% if logged_in? %>
        <li>
          <%= link_to "خروج", logout_path,method: :delete,class:"nav-link text-white" %>
        </li>
        <%else%>
            <%= link_to "رابطة الموظفين", login_path,class:"nav-link text-white" %>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GradProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/navbar'%> <br>
    <% flash.each do |name,msg| %>
    <div class="alert alert-light" role="alert">
      <ul>
        <li> <%= msg %> </li>
      </ul>
      </div>
    <%end%>
    <br>
    <div class = "container">
      <%= yield %>
    </div>
    <br>
  </body>
</html>